<?php if (count($comments['data']) <= 0) { ?>
<div class='comment'>
    <h3>No comments</h3>
    <div class='text'></div>
</div>
<?php } ?>

<?php foreach($comments['data'] as $comment) { ?>
<div class='comment'>
    <h3><?php echo $comment[CommentTbl::TITLE]; ?></h3>
    <h4>
        By <a href='user/view/<?php echo $comment[UserTbl::USERNAME]; ?>'><?php echo $comment[UserTbl::USERNAME]; ?></a>
         on <?php echo date("D, M j, Y, h:ia", $comment[CommentTbl::DATE]); ?>
    </h4>
    <div class='text'><?php echo $comment[CommentTbl::MESSAGE]; ?></div>
    <div class='manage'>
        <?php if (Session::checkPermission(Permissions::SUPER_ADMIN) || (isset($_SESSION[Session::USER_ID]) && $_SESSION[Session::USER_ID] == $comment[CommentTbl::USER_ID])) { ?>
        <input type='button' class='action' value='Delete' onclick='Comments.deleteComment(<?php echo $comment[CommentTbl::ID]; ?>);' />
        <?php } ?>
    </div>
</div>
<?php } ?>

<form action='comment/add' method='post' id='<?php echo CommentController::FORM_ID; ?>'>
    <h3>Add comment</h3>
    <?php Forms::getVerifierField(); ?>
    <input type='hidden' name='<?php echo CommentController::COMMENT_ITEM; ?>' value='<?php echo $comments['id']; ?>' />
    <label for='<?php echo CommentController::COMMENT_TITLE; ?>'>Title</label>
    <input type='text' name='<?php echo CommentController::COMMENT_TITLE; ?>' /><br/>
    <label for='<?php echo CommentController::COMMENT_MESSAGE; ?>'>Message</label>
    <textarea name='<?php echo CommentController::COMMENT_MESSAGE; ?>'></textarea><br/>
    <label></label><input type='submit' value='Submit' />
</form>

<script type='text/javascript'>
    jQuery(document).ready(function() {
        var params = {
            formId: '<?php echo CommentController::FORM_ID; ?>',
            submitMessage: "Adding comment...",
            successAction: function() {
                document.location.reload(true);
            }
        };
        new Form(params);
    });
</script>