<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/tr/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"> 
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <base href='<?php echo WEBROOT; ?>' />
    <title>Site</title>
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    
    <?php self::loadCss('admin.css'); ?>    
    <?php self::loadLib('jquery.min.js'); ?>
    <?php self::loadLib('jquery-ui.min.js'); ?>
    <?php self::loadLib('jquery.history.js'); ?>
    <?php self::loadLib('jquery.form.js'); ?>
    <?php self::loadJs('admin.js'); ?>
</head>
<body>
    <div id='body_wrapper'>
    <div class='container'>

        <div class='user_status'>
        <?php if (Session::isLoggedIn()) { ?>

            <p>You are logged in <a href='user'><?php echo Session::username(); ?></a>.</p>
            <p><a href='admin/logout'>Logout</a></p>

        <?php } else { ?>

            <p><a href='admin/login'>Login</a></p>
            <p><a href='admin/signup'>New user</a></p>
            
        <?php } ?>
        </div>

        <div class='page'>

            <h1>Site</h1>
            <div class='sidebar'>
                <?php
                    $request = new Request();
                    $level1 = $request->getRequestPart(1);
                    $level2 = $request->getRequestPart(2);
                ?>
                <ul>
                    <li class='home<?php if ($level1 == 'home') {echo " sel";} ?>'><a href='<?php echo WEBROOT; ?>'><span></span>Home</a></li>
                    <li class='paperclip<?php if ($level1 == 'admin' && $level2 == 'about') {echo " sel";} ?>'><a href='<?php echo WEBROOT; ?>admin/about'><span></span>About</a></li>

                    <?php if (Session::checkPermission(Permissions::SUPER_ADMIN)) { ?>
                    <li class='admin<?php if ($level1 == 'admin' && empty($level2)) {echo " sel";} ?>'><a href='<?php echo WEBROOT; ?>admin'><span></span>Admin</a>
                        <?php if ($level1 == 'admin') { ?>
                        <ul>
                            <li<?php if ($level1 == 'admin' && $level2 == 'users') {echo " class='sel'";} ?>><a href='admin/users'>- Users</a></li>
                            <li<?php if ($level1 == 'admin' && $level2 == 'requests') {echo " class='sel'";} ?>><a href='admin/requests'>- Requests</a></li>
                            <li<?php if ($level1 == 'admin' && $level2 == 'visitors') {echo " class='sel'";} ?>><a href='admin/visitors'>- Visitors</a></li>
                            <li<?php if ($level1 == 'admin' && $level2 == 'comments') {echo " class='sel'";} ?>><a href='admin/comments'>- Comments</a></li>
                        </ul>
                        <?php } ?>
                    </li>
                    <?php } ?>
                </ul>
            </div><div class='body'>
