<?php $user_info = $this->view->userinfo; ?>
<h3><?php echo $user_info[UserTbl::USERNAME]; ?>'s Profile</h3>

<sheet>
    <row>
        <cell><b>Username</b></cell>
        <cell><?php echo $user_info[UserTbl::USERNAME]; ?></cell>
    </row>
    <?php if (Session::checkPermission(Permissions::SUPER_ADMIN) || $user_info['me']) { ?>
    <row>
        <cell><b>Email</b></cell>
        <cell><?php echo strlen($user_info[UserTbl::EMAIL]) > 0 ? $user_info[UserTbl::EMAIL] : "<i>not provided</i>"; ?></cell>
    </row>
    <?php } ?>
    <row>
        <cell><b>Joined</b></cell>
        <cell><?php echo date("F Y", $user_info[UserTbl::DATE_CREATED]); ?></cell>
    </row>
    <row>
        <cell><b>Posts</b></cell>
        <cell><?php echo $user_info[UserTbl::CUSTOM_POSTS]; ?></cell>
    </row>
</sheet>

<?php if (Session::checkPermission(Permissions::SUPER_ADMIN) || $user_info['me']) { ?>
    <p><a href='user/edit/<?php echo $user_info[UserTbl::USERNAME]; ?>'>Edit Profile</a></p>
<?php } ?>