<h2>Login!</h2>
<?php if($login_form['error']) { ?>
	<p>Incorrect login information.</p>
<?php } ?>
<form action='login' method='post'>
	<?php $login_form['helper']->getVerifierField(); ?>
	<label>Username</label><input type='text' name='<?php echo AuthController::LOGIN_USERNAME; ?>' value='' /><br/>
	<label>Password</label><input type='password' name='<?php echo AuthController::LOGIN_PASSWORD; ?>' value='' /><br/>
	<label></label><input type='submit' value='Login!' />
</form>