<h3>Edit <?php echo $user_info[UserTbl::USERNAME]; ?>'s Profile</h3>

<form action='auth/edit' method='post' id='<?php echo UserController::FORM_ID; ?>'>
	<input type='hidden' name='<?php echo UserController::USER_ID; ?>' value='<?php echo $user_info[UserTbl::ID]; ?>' />
	<label>Username</label>
	<input type='text' name='<?php echo UserController::USER_USERNAME; ?>' value='<?php echo $user_info[UserTbl::USERNAME]; ?>' />
	<br/>
	<label>Email</label>
	<input type='text' name='<?php echo UserController::USER_EMAIL; ?>' value='<?php echo strlen($user_info[UserTbl::EMAIL]) > 0 ? $user_info[UserTbl::EMAIL] : ""; ?>' />
	<br/>
	<h4>Change Password</h4>
	<label>Old Password</label>
	<input type='text' name='<?php echo UserController::USER_OLDPASSWORD; ?>' />
	<br/>
	<label>New Password</label>
	<input type='text' name='<?php echo UserController::USER_NEWPASSWORD; ?>' />
	<br/>
	<label>Verify New Password</label>
	<input type='text' name='<?php echo UserController::USER_VERIFY_NEWPASSWORD; ?>' />
	<br/>
	<label></label><input type='submit' value='Save Changes' />
</form>

<script type='text/javascript'>
	jQuery(document).ready(function() {
		var params = {
			formId: '<?php echo UserController::FORM_ID; ?>',
			submitMessage: "Updating user info...",
			successAction: function() {
				PopupMessage.show({
					message: "Profile updated!",
					buttons: [{
						value: "Ok",
						onclick: 'window.location.href="user/edit/"+jQuery("input[name=<?php echo UserController::USER_USERNAME; ?>]").val();'
					}]
				});
			}
		};
		new Form(params);
	});
</script>