<h3>Edit <?php echo $user_info[UserTbl::USERNAME]; ?>'s Profile</h3>

<form action='user/submit' method='post' id='<?php echo UserController::FORM_ID; ?>'>
	<label>Username</label>
	<input type='text' name='<?php echo UserController::USER_USERNAME; ?>' value='<?php echo $user_info[UserTbl::USERNAME]; ?>' />
	<br/>
	<label>Email</label>
	<input type='text' name='<?php echo UserController::USER_EMAIL; ?>' value='<?php echo strlen($user_info[UserTbl::EMAIL]) > 0 ? $user_info[UserTbl::EMAIL] : ""; ?>' />
	<br/>
	<h4>Change Password</h4>
	<label>Old Password</label>
	<input type='text' name='<?php echo UserController::USER_OLDPASSWORD; ?>' />
	<br/>
	<label>New Password</label>
	<input type='text' name='<?php echo UserController::USER_NEWPASSWORD; ?>' />
	<br/>
	<label>Verify New Password</label>
	<input type='text' name='<?php echo UserController::USER_VERIFY_NEWPASSWORD; ?>' />
	<br/>
	<label></label><input type='submit' value='Save Changes' />
</form>

<?php FormHelper::loadForm(UserController::FORM_ID); ?>