<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/tr/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"> 
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <base href='<?php echo WEBROOT; ?>' />
    <title>App Core Homepage</title>
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    
    <?php self::loadCss('style.css'); ?>    
    <?php self::loadLib('jquery.min.js'); ?>
    <?php self::loadLib('jquery-ui.min.js'); ?>
</head>
<body>
    <div class='container'>